 # schema.yml

version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            description: number for each product
            tests:
              - unique
              - not_null  
          - name: purchSE_PRICE
            description: price of each product
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns:
          - name: date_date
            description: date of purchase
            tests:
              - not_null
          - name: orders_id
            description: number to identify the orders
            tests:
              - not_null
          - name: pdt_id
            description: number given to each product
          - name: revenue
            description: money made from the order
          - name: quantity 
            description: amount of items bought in each order
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: order number
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: how much the client paid for shipping
          - name: shipping_fee_1
            description: cost of shippment again
          - name: logCost
            description: how much it costs to the company to organize the shipping
          - name: ship_cost
      - name: adwords
        identifier: raw_gz_adwords
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: bing
        identifier: raw_gz_bing
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: criteo
        identifier: raw_gz_criteo
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: facebook
        identifier: raw_gz_facebook
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
