 # schema.yml
version: 2
sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: product
        schema: raw_gz_product
      - name: sales
        schema: raw_gz_sales
      - name: ship
        schema: raw_gz_ship