 # schema.yml
version: 2
sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: product
        alias: raw_gz_product
        columns:
          - name: products_id
          - name: purchSE_PRICE 
      - name: sales
        alias: raw_gz_sales
        columns:
          - name: date_date
          - name: orders_id
          - name: pdt_id
          - name: revenue
          - name: quantity 
      - name: ship
        alias: raw_gz_ship
        columns:
          - name: orders_id
          - name: shipping_fee
          - name: shipping_fee_1
          - name: logCost
          - name: ship_cost